### ISSUE TITLE
WANT THE OIL SPILL DATASET IMAGES

### ISSUE THREAD

**Issue by 31priyanka03** [AlHashmiMohamed/BEng-Final-Year-Project#1]
Hey Programmer,  I am working on this project. I will be thankful if you provide me with the dataset regarding the same project. Please respond if you are looking at the comment. send an email of the dataset or you can update it on the shared repository.                   
EMAIL ADDRESS - **laadpriyanka2003@gmail.com**

**Comment by AlHashmiMohamed** [comment]
Dear 31priyanka03, 

Even though the Sentinel-1 images are openly available, I cannot share the dataset for confidentiality reasons. However, please check out NESDIS Marine Pollution oil spill reports at [https://www.ospo.noaa.gov/Products/ocean/marinepollution/](url). They provide oil spill reports that include the location and extent of the oil spill and the satellite acquisition/scene name.

Thanks,

Mohamed
